apiVersion: apps/v1
kind: Deployment
metadata:
  name: digs-microservice-deployment
  labels:
    app: digs-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digs-microservice
  template:
    metadata:
      labels:
        app: digs-microservice
    spec:
      imagePullSecrets:
      - name: docker-hub-private
      containers:
      - name: digs-microservice
        image: kingslysg/digs-microservice
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: digs-microservice-srv
  labels:
    app: digs-microservice-srv
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
  selector:
    app: digs-microservice-srv