apiVersion: apps/v1
kind: Deployment
metadata:
  name: digs-microservice
  labels:
    app: digs-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digs-microservice
  template:
    metadata:
      labels:
        app: digs-microservice
    spec:
      imagePullSecrets:
      - name: docker-hub-private
      containers:
      - name: digs-microservice
        image: kingslysg/digs-microservice

---
apiVersion: v1
kind: Service
metadata:
  name: digs-microservice-ngix
  labels:
    app: digs-microservice
spec:
  ports:
  - protocol: TCP
    port: 31000
    targetPort: 80
    nodePort: 31500
  type: NodePort
  selector:
    app: digs-microservice